=== JasonLukacs/uCSerial/include/uCSerial/msgparser/rules_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "startMsg": {
      "type": "string",
      "maxLength": 1
    },
    "stopMsg": {
      "type": "string",
      "maxLength": 1
    },
    "startValue": {
      "type": "string",
      "maxLength": 1
    },
    "stopValue": {
      "type": "string",
      "maxLength": 1
    },
    "valueRules": {
      "type": "object",
      "patternProperties": {
        ".+": {
          "type": "object",
          "properties": {
            "msgDescriptor": {
              "type": "string",
              "maxLength": 32
            },
            "minValue": {
              "type": "integer",
              "minimum": -2147483647,
              "maximum": 2147483647
            },
            "maxValue": {
              "type": "integer",
              "minimum": -2147483647,
              "maximum": 2147483647
            }
          },
          "required": [
            "msgDescriptor",
            "minValue",
            "maxValue"
          ]
        }
      }
    }
  },
  "required": [
    "startMsg",
    "stopMsg",
    "startValue",
    "stopValue",
    "valueRules"
  ]
}

=== JasonLukacs/uCSerial/config/msg_rules.json
{
  "startMsg": "{",
  "stopMsg": "}",
  "startValue": "<",
  "stopValue": ">",
  "valueRules": {
    "RBA": {
      "msgDescriptor": "Raw byte 1",
      "minValue": 0,
      "maxValue": 255
    },
    "RBB": {
      "msgDescriptor": "Raw byte 2",
      "minValue": 0,
      "maxValue": 255
    },
    "RBC": {
      "msgDescriptor": "Raw byte 3",
      "minValue": 0,
      "maxValue": 255
    },
    "RBD": {
      "msgDescriptor": "Raw byte 4",
      "minValue": 0,
      "maxValue": 255
    },
    "RBE": {
      "msgDescriptor": "Raw byte 5",
      "minValue": 0,
      "maxValue": 255
    },
    "RBF": {
      "msgDescriptor": "Raw byte 6",
      "minValue": 0,
      "maxValue": 255
    },
    "RBG": {
      "msgDescriptor": "Raw byte 7",
      "minValue": 0,
      "maxValue": 255
    },
    "RBH": {
      "msgDescriptor": "Raw byte 8",
      "minValue": 0,
      "maxValue": 255
    },
    "ADT": {
      "msgDescriptor": "ADC T",
      "minValue": 400000,
      "maxValue": 600000
    },
    "ADP": {
      "msgDescriptor": "ADC P",
      "minValue": 200000,
      "maxValue": 400000
    },
    "ADH": {
      "msgDescriptor": "ADC H",
      "minValue": 20000,
      "maxValue": 40000
    },
    "RFT": {
      "msgDescriptor": "Reference temperature",
      "minValue": -500,
      "maxValue": 4500
    },
    "RFP": {
      "msgDescriptor": "Reference pressure",
      "minValue": 95000,
      "maxValue": 105000
    },
    "RFH": {
      "msgDescriptor": "Reference humidity",
      "minValue": 0,
      "maxValue": 10000
    }
  }
}
